apiVersion: apps/v1
# Deployment
kind: Deployment
metadata:
  name: test-dep-02
  namespace: test-ns-02
spec:
  replicas: 4
  # Will select label
  selector:
    matchLabels:
      deployedBy: test-dep-02
  # Pod
  template:
    metadata:
      # label to specify in order to be retrieved by the Deployment
      labels:
        deployedBy: test-dep-02
        exposedBy: test-service
    spec:
      containers:
        - name: test-container-01
          image: 28a3c4c50c4d/python-docker:0.1.0
          ports:
            - containerPort: 5000

          # Node startup
          startupProbe:
            httpGet:
              path: /prout/albertq
              port: 5000
            failureThreshold: 5
            periodSeconds: 10

          # Node started but app ready ?
          readinessProbe:
            httpGet:
              path: /prout/albertq
              port: 5000
            initialDelaySeconds: 1
            periodSeconds: 20

          # Node started and app ready, check-up
          livenessProbe:
            httpGet:
              path: /prout/albertq
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 120
