apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"test-service","namespace":"test-ns-02"},"spec":{"ports":[{"port":5000,"protocol":"TCP","targetPort":5000}],"selector":{"exposedBy":"test-service"}}}
  creationTimestamp: "2022-08-17T10:59:44Z"
  name: test-service
  namespace: test-ns-02
  resourceVersion: "505996"
  uid: a23b4d40-ec4a-42c4-9706-a141a3fe5613
spec:
  clusterIP: 10.12.13.32
  clusterIPs:
  - 10.12.13.32
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    exposedBy: test-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
