apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"test-ns-01"}}
  creationTimestamp: "2022-08-17T07:38:50Z"
  labels:
    kubernetes.io/metadata.name: test-ns-01
  name: test-ns-01
  resourceVersion: "419627"
  uid: 5effcd57-2c5b-4e8b-b830-75cf1f255d26
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
