apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"test-dep-01","namespace":"test-ns-02"},"spec":{"replicas":4,"selector":{"matchLabels":{"app":"python-docker"}},"template":{"metadata":{"labels":{"app":"python-docker"}},"spec":{"containers":[{"image":"28a3c4c50c4d/python-docker:0.1.0","livenessProbe":{"httpGet":{"path":"/prout/albertq","port":5000},"initialDelaySeconds":120,"periodSeconds":120},"name":"test-container-01","ports":[{"containerPort":5000}]}]}}}}
  creationTimestamp: "2022-08-17T08:21:34Z"
  generation: 1
  name: test-dep-01
  namespace: test-ns-02
  resourceVersion: "437986"
  uid: 21291236-3926-4477-abcc-091c5268c0b1
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: python-docker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-docker
    spec:
      containers:
      - image: 28a3c4c50c4d/python-docker:0.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /prout/albertq
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 1
        name: test-container-01
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2022-08-17T08:21:36Z"
    lastUpdateTime: "2022-08-17T08:21:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-08-17T08:21:34Z"
    lastUpdateTime: "2022-08-17T08:21:36Z"
    message: ReplicaSet "test-dep-01-559fcd85c6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
